server:
  port: 8081
  forward-headers-strategy: framework

spring:
  application:
    name: bigdata

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:mem:testdb

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

  jackson:
    deserialization:
      fail-on-unknown-properties: true

##logging settings
logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n'

  level:
    root: WARN
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO